title: Roderick Lab
email: contact@rodericklab.org  # or appropriate lab contact
description: Research website of the Roderick Lab

# baseurl MUST be set to the repository name because site is served at:
# https://rodericklab.github.io/rodericklab/
baseurl: "/rodericklab"

# The full URL of the site without trailing slash
url: "https://rodericklab.github.io"

# Footer info: adapt to lab details
affiliation: >
  Roderick Lab<br/>
  Department of Cardiovascular Sciences<br/>
  KU Leuven

location: >
  KU Leuven<br/>
  Herestraat 49<br/>
  3000 Leuven, Belgium

contact: >
  <a href="mailto:contact@rodericklab.org" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact the Roderick Lab</a> <br/>
  <a href="https://github.com/rodericklab/rodericklab"><i class="fa fa-github fa-1x"></i> Source code for this site</a>



# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: talks
  - name: research
  - name: software
  - name: team
  - name: teaching
  - name: blogs

# Files and folders to include when building the site
include:
  - .htaccess
  - _pages

# C# Markdown processing settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

# Plugins used
plugins:
  - jekyll-scholar

# Configuration for jekyll-scholar plugin for bibliography management
scholar:
  last_name: Doe
  first_name: [John]

  style: citestyle 
  locale: en

  source: assets    # Removed leading slash for relative path consistency
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

# Exclude these files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - update_bootstrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
